on:
    push:
        tags:
            - 'v*'

name: Publish Datapacks

jobs:
    zip:
        name: Zip Datapacks
        runs-on: ubuntu-latest

        steps:
            - name: Checkout Code
              uses: actions/checkout@master

            - name: Set Script Permissions
              run: chmod +x ./zip_dirs.sh
            
            - name: Zip Datapacks
              run: ./zip_dirs.sh

            - name: Create Release
              uses: softprops/action-gh-release@v2
              with:
                name: Datapack Release ${{ github.ref }}
                body: Datapacks for the Minecraft version based on the first three numbers of the tag i.e. for 1.21.9.x the version is 1.21.9
                draft: true
                prerelease: false
                files: |
                  *.zip
